name: model-soil-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip<=25.0
  - numpy=1.24
  - pandas=1.4.3
  - scikit-learn=1.3.0
  - psutil=5.9.0
  - scipy=1.10.0
  - cloudpickle=3.1.1
  - pip:
      - mlflow==2.19.0
