name: model-soil-env
channels:
  - conda-forge
dependencies:
  - python=3.12.3
  - pip<=25.0
  - numpy==1.6.4
  - pandas==1.4.3
  - scikit_learn==1.6.1
  - psutil==7.0.0
  - scipy==1.15.3
  - cloudpickle==3.1.1
  - pip:
      - mlflow==2.19.0
